---
- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elasticsearch repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main" state=present

- name: Make sure kibana is present
  apt: name=kibana state=present
  notify: 
    - install x-pack
    - restart kibana

- name: Copy kibana configuration
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml mode=0744
  notify:
    - restart kibana